### ISSUE TITLE
questions about metacell analysis

### ISSUE THREAD

**Issue by Peasent007** [GfellerLab/MetacellAnalysisToolkit#11]
Wow! You did a great analysis pipeline which i want to do. Thank you for your great job.
And, i want to discuss some questions about metacell analysis as following:

**Comment by Peasent007** [comment]
1. How can we confirm the rationality of result after combine cells by metacell analysis? if this analysis can import error metacell that maybe a doublet cell.
2. Is there any great methods for batch effect correction? Should we do that before or after metacell analysis?

**Comment by leonardHerault** [comment]
Dear Peasant,

Tanks for trying our pipeline I understand that you are speaking about the atlas integration [unsupervised](https://github.com/GfellerLab/MetacellAnalysisToolkit/blob/main/examples/HLCA_core_atlas.md) and [supervised](https://github.com/GfellerLab/MetacellAnalysisToolkit/blob/main/examples/HLCA_core_atlas_supervised.md) analyses.

Always keep in mind that metacells are not perfect and can present some impurities potentially biasing downstream analyses especially integration/batch correction. 

To limit this bias we recommend to use reasonable graining level (between 10 and 50) and single cell annotation if available to build supervised metacells in each cell type. Then, the derived metacell annotations can then be used to guide batch correction with tools such as [STACAS](https://github.com/carmonalab/STACAS) or scanvi.

Batch correction metrics such as average cell type silhouette or CiLISI can be used to check that integration correctly remove batch effect without mixing cell type (again if annotations are available).

For reducing the computational burden, batch correction should be performed on metacells build in each batch as we did in the lung atlas example.

If you have enough resources to correct batch effect at the single cell levels, you could be more interested in reducing the size and the sparsity of the btach corrected dataset. For this you can build metacells based on the corrected embedding, preferably in each batch to facilitate downstream analyses.

In our hands anchor based methods (SeuratRPCA, STACAS) work well both on single-cells and metacells and STACAS present the advantage of offering a (semi-)-supervised batch correction if you have your dataset partially or completely annotated. 

Best,

LH

**Comment by ZengFLab** [comment]
> 1. How can we confirm the rationality of result after combine cells by metacell analysis? if this analysis can import error metacell that maybe a doublet cell.
> 2. Is there any great methods for batch effect correction? Should we do that before or after metacell analysis?

You can take a try of our method SURE design for metacell calling and cell atlas assembly (including integration). https://github.com/ZengFLab/SUREv2
