### ISSUE TITLE
MetaCell Purity Score

### ISSUE THREAD

**Issue by hl-xue** [GfellerLab/MetacellAnalysisToolkit#12]
Hello,

Thanks for developing this nice workflow!

I may have a question regarding the metacell purity, please.
I was using SuperCell mode without providing the `.obs` column name of cell type annotation. But I still got a cell type purity score column in my output. I would like to know how did SuperCell identify the cell type annotation column, and can I rely on the computed purity values in this column, please ?

Thanks again and Kind regards!

**Comment by leonardHerault** [comment]
Dear hl-xue,

Thanks for using our tool.
MCAT will automatically compute purity scores for each character column of .obs (or @metada for seurat object) of the single cell object and yes you can rely on these values. 

Best

lh

**Comment by hl-xue** [comment]
OK, understand, thanks!
