### ISSUE TITLE
Possible to remove the dependence of Anaconda default channel?

### ISSUE THREAD

**Issue by hl-xue** [GfellerLab/MetacellAnalysisToolkit#13]
Hello,

Following the anaconda license change, some institutes may not be able to freely use the "defaults" channel from Anaconda (as explained [here - *The default Channel and Anaconda’s Terms of Service*](https://www.anaconda.com/blog/is-conda-free)). So, I was wondering is it possible to remove the dependence of that channel from the installation of MATK (e.g., conda yaml and docker file), please?

Thanks in advance!

Kind regards,
Haoliang

**Comment by leonardHerault** [comment]
Dear Haoliang,

Thank you for pointing out this change in the anaconda license.
We have been using anaconda in the docker file to make the build easier and faster, but it should be possible to do without it.
As we're planning major updates to our tools in the coming months, we will consider update the docker file without anaconda at that time.

Best

Léonard

**Comment by hl-xue** [comment]
Dear Léonard,

Great, thank you very much!
Looking forward to seeing your new updates for the super tool! Good luck!

Kind regards,
Haoliang
