### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by victorcat4** [GfellerLab/MetacellAnalysisToolkit#3]
Hello,

 Thank you very much for this very clear review and this usefull tool you provide. 
 
 Would it be possible to provide a docker image with it ?

**Comment by aurelieGabriel** [comment]
Hello,
Thank you for your feedback. A docker file (env/Dockerfile_MATK) was added as well as instructions in the README to run MATK within the corresponding docker container.
Best regards.

**Comment by victorcat4** [comment]
Great, thank you !
