### ISSUE TITLE
Input data 

### ISSUE THREAD

**Issue by victorcat4** [GfellerLab/MetacellAnalysisToolkit#5]
Hello, 

I've been using the docker to run MATK which works perfectly for provided data. However, when using my Seurat object, MATK no longer works.
My seurat object was build this way 
```
> seurat <- CreateSeuratObject(counts = raw_cm, meta.data = metadata_df, assay="RNA")`
> seurat
An object of class Seurat 
19696 features across 47423 samples within 1 assay 
Active assay: RNA (19696 features, 0 variable features)
 1 layer present: counts
```
But when running MATK : 
```
Normalize data...Error in GetAssay.Seurat(object = object, assay = assay) : 
  RNA is not an assay present in the given object. Available assays are: 
Calls: NormalizeData ... NormalizeData.Seurat -> GetAssay -> GetAssay.Seurat
Execution halted
```
 I tried with my datasets but also public ones. 
 
Could you provide a line of code to go from count matrix and metadata, to seurat and anndata object suitable for MATK ?

Best regards and thanks again for this useful tool!

**Comment by leonardHerault** [comment]
Hi Victorcat4,

Thank you very much for your interest in our tool!

Your Seurat object was created with Seurat v5 (with layer).
Did you use the docker with Seurat v5 (agabriel/matk:v1.1)? I suspect you used the docker with Seurat v4.

For MATK, we've worked on making Seurat v4 objects compatible with the Seurat v5 package, but we can't make objects created with layers (v5) usable in a Seurat v4 environment.

A workaround for you without reinstalling anything would be to convert your v5 object into a v4 after creating it using Seurat v5:
` as(object = sobjMC[["RNA"]], Class = "Assay")`

Then you should be able to use the docker with seurat v4 that you installed.

But I think the best option is now to switch completely to Seurat v5 and we will update our documentation accordingly.

Best

**Comment by victorcat4** [comment]
Thanks ! 
So using the docker `agabriel/matk:v1.1` solved the problem for Supercell however SEACell is still crashing.
Code
```
docker run --rm \
        -v $(pwd):/workspace \
        agabriel/matk:v1.1 \
        MATK -t SEACells \
        -i /workspace/data/sc_23.rds \
        -o /workspace/MATK_output/SEACell/g_${granularity}/ \
        -n 50 \
        -f 2000 \
        -k 30 \
        -g ${granularity} \
        -s seurat
```
error 
```
Running SEACell for granularity 75
SEACells
/workspace/data/sc_23.rds
Identifying metacells...
input is " /workspace/data/sc_23.rds
Output dir is " /workspace/MATK_output/SEACell/g_75/
gamma is " 75.0
dims are " 50
reduction_key is" X_pca

    WARNING: The R package "reticulate" only fixed recently
    an issue that caused a segfault when used with rpy2:
    https://github.com/rstudio/reticulate/pull/1188
    Make sure that you use a version of that package that includes
    the fix.
    Traceback (most recent call last):
  File "/MetacellAnalysisToolkit/cli/SEACellsCL.py", line 270, in <module>
    main(sys.argv[1:])
  File "/MetacellAnalysisToolkit/cli/SEACellsCL.py", line 89, in main
    del adata.layers['logcounts']  # we only load raw counts stored in adata.X when using as.SingleCellExperiment and annadata2ri
  File "/opt/conda/envs/MetacellAnalysisToolkit/lib/python3.9/site-packages/anndata/_core/aligned_mapping.py", line 188, in __delitem__
    del self._data[key]
KeyError: 'logcounts'
```

**Comment by leonardHerault** [comment]
Yes, I corrected this error with a commit one hour ago.
If you pull the changes it should work for SEACells now.
